Commit first
rrEmiZ/UITMBER.Api pull request #8
Opened 2021-01-25 15:08 UTC by Vladhus

Added Controller ,Repo

2021-01-25 15:09 UTC, Vladhus commented
w60047

2021-01-27 10:56 UTC, rrEmiZ requested changes
Missing Repository DI register

2021-01-27 20:55 UTC, Vladhus commented
> Missing Repository DI register

What does it mean?

2021-01-28 08:57 UTC, rrEmiZ commented
Repository was not registered in services at StartUp.

2021-02-19 08:16 UTC, closed without merging